# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_upload_shader.ipynb.

# %% auto 0
__all__ = ['start_time', 'debug', 'cm']

# %% ../00_upload_shader.ipynb 0
# |export
#|default_exp p00_upload_shader


# %% ../00_upload_shader.ipynb 1
import time
from helium import *



# %% ../00_upload_shader.ipynb 2
start_time=time.time()
debug=True
_code_git_version="2b944bad10b28b892248b8c76245d13b9d666896"
_code_repository="https://github.com/plops/cl-py-generator/tree/master/example/56_myhdl/source/04_tang_lcd/run_04_lcd.py"
_code_generation_time="20:51:25 of Wednesday, 2022-08-17 (GMT+1)"
start_time=time.time()
debug=True


# %% ../00_upload_shader.ipynb 3
start_chrome("https://www.shadertoy.com/view/7t3cDs", headless=False)


# %% ../00_upload_shader.ipynb 4
cm=S("//div[contains(@class,'CodeMirror')]")
click(cm)
list(map(lambda x: press(ARROW_UP), range(12)))
list(map(lambda x: press(((SHIFT)+(DELETE))), range(12)))
write("void mainImage")

