# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

USE="-vaapi -doc -cups -opencl -jemalloc -wayland"
VIDEO_CARDS="nvidia radeonsi amdgpu"
LLVM_TARGETS="X86 NVPTX AMDGPU"

ACCEPT_LICENSE="*"

# Appending getbinpkg to the list of values within the FEATURES variable
FEATURES="${FEATURES} getbinpkg"
# Require signatures
FEATURES="${FEATURES} binpkg-request-signature"

GENTOO_MIRRORS="https://pkg.adfinis-on-exoscale.ch/gentoo/ \
    http://pkg.adfinis-on-exoscale.ch/gentoo/ \
    https://ch.mirrors.cicku.me/gentoo/ \
    http://ch.mirrors.cicku.me/gentoo/ \
    https://mirror.init7.net/gentoo/ \
    http://mirror.init7.net/gentoo/ \
    rsync://mirror.init7.net/gentoo/"
