[project]
name = "163-fasthtml-sse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "python-fasthtml>=0.12.29",
]
