# AUTOGENERATED! DO NOT EDIT! File to edit: 005_tests_functional.ipynb (unless otherwise specified).

__all__ = ['browser']

# Cell
# pip3 install --user selenium
# https://github.com/mozilla/geckodriver/releases
# wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
# tar xaf geckodriver*.tar.gz
# sudo cp geckodriver /usr/local/bin
from selenium import webdriver
browser=webdriver.Firefox()
browser.get("http://localhost:8000")
assert(("PyGram" in browser.title))
