# AUTOGENERATED! DO NOT EDIT! File to edit: 005_tests_functional.ipynb (unless otherwise specified).

__all__ = ['NewVisitorTest']

# Cell
# pip3 install --user selenium
# https://github.com/mozilla/geckodriver/releases
# wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
# tar xaf geckodriver*.tar.gz
# sudo cp geckodriver /usr/local/bin
# follow textbook 2017 Test-Driven Development with Python
import unittest
from selenium import webdriver
class NewVisitorTest(unittest.TestCase):
    def setUp(self):
        self.browser=webdriver.Firefox()
    def tearDown(self):
        self.browser.quit()
    def test_can_create_post_and_retrieve_it_later(self):
        self.browser.get("http://localhost:8000")
        self.assertIn("PyGram", self.browser.title)
        self.fail("Finish the test!")
if ( ((__name__)==("__main__")) ):
    unittest.main(warnings="ignore")
