// File: lcd.v
// Generated by MyHDL 0.11
// Date: Fri Jun 18 16:24:28 2021


`timescale 1ns/10ps

module lcd (
    pixel_clk,
    n_rst,
    lcd_de,
    lcd_hsync,
    lcd_vsync,
    lcd_r,
    lcd_g,
    lcd_b
);


input pixel_clk;
input n_rst;
output lcd_de;
reg lcd_de;
output lcd_hsync;
reg lcd_hsync;
output lcd_vsync;
reg lcd_vsync;
output lcd_r;
reg lcd_r;
output lcd_g;
reg lcd_g;
output lcd_b;
reg lcd_b;

reg [9:0] pixel_count;
reg [9:0] line_count;



always @(posedge pixel_clk, negedge n_rst) begin: LCD_LOGIC_COUNT
    if ((n_rst == 0)) begin
        line_count <= 0;
        pixel_count <= 0;
    end
    else begin
        if ((pixel_count == 872)) begin
            line_count <= (line_count + 1);
            pixel_count <= 0;
        end
        else begin
            if ((line_count == 340)) begin
                line_count <= 0;
                pixel_count <= 0;
            end
            else begin
                pixel_count <= (pixel_count + 1);
            end
        end
    end
end


always @(line_count, pixel_count) begin: LCD_LOGIC_SYNC
    if (((1 <= pixel_count) & (pixel_count <= (480 + 182)))) begin
        lcd_hsync = 0;
    end
    else begin
        lcd_hsync = 1;
    end
    if (((5 <= line_count) & (line_count <= 340))) begin
        lcd_vsync = 0;
    end
    else begin
        lcd_vsync = 1;
    end
    if ((((182 <= pixel_count) & (pixel_count <= (480 + 182))) & ((6 <= line_count) & (line_count <= (272 + 5))))) begin
        lcd_de = 1;
    end
    else begin
        lcd_de = 0;
    end
end


always @(pixel_count) begin: LCD_LOGIC_PATTERN
    if ((pixel_count < 240)) begin
        lcd_r = 1;
    end
    else if ((pixel_count < 480)) begin
        lcd_g = 1;
    end
    else if ((pixel_count < 600)) begin
        lcd_b = 1;
    end
    else begin
        lcd_r = 0;
        lcd_g = 0;
        lcd_b = 0;
    end
end

endmodule
