# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Post": "001_posts_models.ipynb",
         "Comment": "001_posts_models.ipynb",
         "PostList": "002_posts_views.ipynb",
         "PostCreate": "002_posts_views.ipynb",
         "CommentForm": "002_posts_views.ipynb",
         "PostDetail": "002_posts_views.ipynb",
         "urlpatterns": "003_pygram_urls.ipynb",
         "browser": "005_tests_functional.ipynb"}

modules = ["posts/models.py",
           "posts/views.py",
           "pygram/urls.py",
           "posts/admin.py",
           "tests/functional.py"]

doc_url = "https://plops.github.io/web/"

git_url = "https://github.com/plops/web/tree/master/"

def custom_doc_links(name): return None
