/* Generated by nMigen Yosys 0.9+3746 (PyPI ver 0.9.post3746.dev31, git sha1 95c60866) */

(* \nmigen.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "nMigen" *)
module top(ovf, clk, rst, en);
  reg \initial  = 0;
  (* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:32" *)
  wire \$1 ;
  (* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:37" *)
  wire [5:0] \$3 ;
  (* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:37" *)
  wire [5:0] \$4 ;
  (* src = "/home/martin/.local/lib/python3.9/site-packages/nmigen/hdl/ir.py:524" *)
  input clk;
  (* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:28" *)
  reg [4:0] count = 5'h00;
  (* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:28" *)
  reg [4:0] \count$next ;
  (* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:26" *)
  input en;
  (* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:27" *)
  output ovf;
  (* src = "/home/martin/.local/lib/python3.9/site-packages/nmigen/hdl/ir.py:524" *)
  input rst;
  assign \$1  = count == (* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:32" *) 5'h19;
  assign \$4  = count + (* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:37" *) 1'h1;
  always @(posedge clk)
    count <= \count$next ;
  always @* begin
    if (\initial ) begin end
    \count$next  = count;
    (* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:33" *)
    casez (en)
      /* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:33" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:34" *)
          casez (ovf)
            /* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:34" */
            1'h1:
                \count$next  = 5'h00;
            /* src = "/home/martin/stage/cl-py-generator/example/59_nmigen/source/00_first/run_00_first.py:36" */
            default:
                \count$next  = \$3 [4:0];
          endcase
    endcase
    (* src = "/home/martin/.local/lib/python3.9/site-packages/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \count$next  = 5'h00;
    endcase
  end
  assign \$3  = \$4 ;
  assign ovf = \$1 ;
endmodule
