# AUTOGENERATED! DO NOT EDIT! File to edit: 004_posts_admin.ipynb (unless otherwise specified).

__all__ = []

# Cell
from django.contrib import admin
from posts.models import Post
admin.site.register(Post, admin.ModelAdmin)
