# AUTOGENERATED! DO NOT EDIT! File to edit: 001_posts_models.ipynb (unless otherwise specified).

__all__ = ['Post', 'Comment']

# Cell
from django.db import models
from django.contrib.auth.models import User


# Cell
# the class is a table and each element is a column in the table
class Post(models.Model):
    image=models.ImageField()
    description=models.TextField()
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    created=models.DateTimeField
    auto_now_added=True
    modified=models.DateTimeField
    auto_now_added=True
class Comment(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE)
    text=models.TextField()
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    created=models.DateTimeField
    auto_now_added=True
    modified=models.DateTimeField
    auto_now_added=True
