// File: leds.v
// Generated by MyHDL 0.11
// Date: Thu Jun 10 23:20:43 2021


`timescale 1ns/10ps

module leds (
    sys_clk,
    sys_rst_n,
    led
);


input sys_clk;
input sys_rst_n;
output [2:0] led;
reg [2:0] led;

reg [20:0] counter;



always @(posedge sys_clk, negedge sys_rst_n) begin: LEDS_LOGIC
    if ((sys_rst_n == 0)) begin
        counter <= 0;
    end
    else begin
        if ((counter < 1999999)) begin
            counter <= (counter + 1);
        end
        else begin
            counter <= 0;
        end
    end
end


always @(posedge sys_clk, negedge sys_rst_n) begin: LEDS_LOGIC_LED
    if ((sys_rst_n == 0)) begin
        led <= 3'h6;
    end
    else begin
        if ((counter == 1999999)) begin
            led[3-1:0] <= {led[2-1:0], led[1-1:0]};
        end
        else begin
            led <= led;
        end
    end
end

endmodule
