# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_titanic_from_scratch.ipynb.

# %% auto 0
__all__ = ['start_time', 'debug', 'parser', 'args', 'path', 'line_char_width', 'df', 'mode']

# %% ../00_titanic_from_scratch.ipynb 0
# |export
#|default_exp p00_titanic_from_scratch


# %% ../00_titanic_from_scratch.ipynb 1
import os
import time
import pathlib
import argparse



# %% ../00_titanic_from_scratch.ipynb 2
start_time=time.time()
debug=True
_code_git_version="dc25f95f025eb1bc3df703b6a2f94876f52bc097"
_code_repository="https://github.com/plops/cl-py-generator/tree/master/example/96_colab_fastai/source/"
_code_generation_time="23:03:02 of Saturday, 2022-08-27 (GMT+1)"
start_time=time.time()
debug=True


# %% ../00_titanic_from_scratch.ipynb 3
parser=argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="enable verbose output", action="store_true")
args=parser.parse_args()


# %% ../00_titanic_from_scratch.ipynb 4
path=pathlib.Path("titanic")
if ( not(path.exists()) ):
    import zipfile
    import kaggle
    kaggle.api.competition_download_cli(str(path))
    zipfile.ZipFile(f"{path}.zip").extractall(path)


# %% ../00_titanic_from_scratch.ipynb 5
import torch
import numpy as np
import pandas as pd
line_char_width=140
np.set_print_options(linewidth=line_char_width)
torch.set_print_options(linewidth=line_char_width, sci_mode=False, edgeitems=7)
pd.set_option("display_width", line_char_width)


# %% ../00_titanic_from_scratch.ipynb 6
df=pd.read_csv(((path)/("train.csv")))
df


# %% ../00_titanic_from_scratch.ipynb 8
mode=df.mode().iloc[0]


# %% ../00_titanic_from_scratch.ipynb 9
df.fillna(modes, inplace=True)

