// File: mem.v
// Generated by MyHDL 0.11
// Date: Sat Jun 19 12:58:19 2021


`timescale 1ns/10ps

module mem (
    clk,
    adr,
    we,
    di,
    do
);


input clk;
input [7:0] adr;
input we;
input [7:0] di;
output [7:0] do;
reg [7:0] do;

reg [7:0] ram [0:256-1];


