// File: processor.v
// Generated by MyHDL 0.11
// Date: Thu Jun 17 17:48:44 2021


`timescale 1ns/10ps

module processor (
    clk,
    rst,
    di,
    do,
    adr,
    we
);


input clk;
input rst;
input [7:0] di;
input [7:0] do;
output [15:0] adr;
reg [15:0] adr;
output we;
reg we;

reg [7:0] am;
reg [2:0] cyc;
reg [7:0] im;
reg [7:0] ir;
reg [10:0] pc;
reg [7:0] ra;
reg [7:0] rw;
wire [7:0] rx;
reg [7:0] sr;

assign rx = 8'd0;


always @(posedge clk) begin: PROCESSOR_LOGIC
    if (rst) begin
        pc <= 0;
        adr <= 0;
    end
    else if ((cyc == 0)) begin
        adr <= (pc + 1);
        pc <= (pc + 1);
        cyc <= 1;
    end
    else if ((cyc == 1)) begin
        adr <= (pc + 1);
        ir <= do;
        cyc <= 2;
    end
    else if ((cyc == 2)) begin
        im <= do;
        am <= (ir & 7);
        ir <= ((ir >>> 3) & 31);
        cyc <= 3;
    end
    else if ((cyc == 4)) begin
        if (1'b1) begin
            we <= 0;
            adr <= pc;
        end
        cyc <= 5;
    end
    else if ((cyc == 5)) begin
        if ((ir == 17)) begin
            ra <= do;
            sr <= {(128 <= do), (do == 0), sr[6-1:0]};
        end
        else if ((rw == 0)) begin
            sr <= {(128 <= ra), (ra == 0), sr[6-1:0]};
        end
        else if ((rw == 1)) begin
            sr <= {(128 <= ra), (rx == 0), sr[6-1:0]};
        end
        if ((ir == 23)) begin
            pc <= ((do << 8) | (pc & 255));
            adr <= ((do << 8) | (pc & 255));
        end
        else begin
            adr <= pc;
        end
        we <= 0;
        rw <= 0;
        cyc <= 0;
    end
end

endmodule
