#!/usr/bin/perl
use strict;
use warnings;
use URI::Escape;
use File::Basename;
use Getopt::Long;

# Configuration
my $toplevel_dir = "/squashfs-root"; 

# Options
my $opt_uncompressed = 0;
my $opt_ratio = 0;

GetOptions(
    "uncompressed" => \$opt_uncompressed,
    "ratio"        => \$opt_ratio
) or die("Error in command line arguments\n");

print <<EOF;
[qdirstat 2.0 cache file]
# Generated by 7z-to-qdirstat
# Type  path  size  uid  gid  perm  mtime
EOF

my %dirs;
my %files;
my $parsing_started = 0;

while (<>) {
    chomp;

    # 1. State Machine: Wait for separator
    if (/^-------------------/) {
        $parsing_started = 1;
        next;
    }
    next unless $parsing_started;

    # 2. Validation: Ensure line starts with a timestamp
    next unless /^\d{4}-\d{2}-\d{2}/;

    my $line = $_;
    
    # 3. Parse Columns: Date(0) Time(1) Attr(2) ...
    my ($date, $time, $attr, $rest) = split(/\s+/, $line, 4);

    next unless defined $attr;
    $rest =~ s/^\s+//;

    # CASE A: Directory
    if ($attr =~ /^D/) {
        my $path = $rest;
        $path = "$toplevel_dir/$path"; 
        $path =~ s|/$||;
        $dirs{$path} = 1;
        next;
    }

    # CASE B: File
    # $rest contains: "Size   Compressed  Name"
    my ($size, $compressed, $name) = split(/\s+/, $rest, 3);
    
    next unless defined $name;

    # Data cleanup
    $size       = 0 unless ($size =~ /^\d+$/);
    $compressed = 0 unless ($compressed =~ /^\d+$/);

    # Determine visual size based on flags
    my $visual_size = $compressed; # Default

    if ($opt_uncompressed) {
        $visual_size = $size;
    } elsif ($opt_ratio) {
        if ($size > 0) {
            # Ratio as integer percentage (e.g. 45% -> 45).
            # Note: Treemaps sum these, so folder sizes will be nonsense (sum of percentages).
            $visual_size = int(($compressed / $size) * 100);
        } else {
            $visual_size = 0;
        }
    }

    # Normalize path
    my $full_path = "$toplevel_dir/$name";
    my $dir       = dirname($full_path);
    my $filename  = basename($full_path);

    $dirs{$dir} = 1;

    push @{$files{$dir}}, [$filename, $visual_size];
}

# Output
foreach my $dir (sort keys %dirs) {
    my $enc_dir = uri_escape($dir, "\x00-\x20%");
    print "D $enc_dir\t0\t0\t0\t0755\t0\n";

    if (exists $files{$dir}) {
        foreach my $file_ref (@{$files{$dir}}) {
            my ($name, $val) = @$file_ref;
            my $enc_name = uri_escape($name, "\x00-\x20%");
            print "F $enc_name\t$val\t0\t0\t0644\t0\n";
        }
    }
}
