#!/usr/bin/perl
use strict;
use warnings;
use URI::Escape;
use File::Basename;

# Configuration
my $toplevel_dir = "/squashfs-root"; # Virtual root name for the visualization
my $target_col   = 4; # 0-indexed column for 'Compressed' in your specific 7z output

print <<EOF;
[qdirstat 2.0 cache file]
# Generated by 7z-to-qdirstat
# Type  path  size  uid  gid  perm  mtime
EOF

my %dirs;
my %files;

while (<>) {
    chomp;
    next if /^\s*Date\s+Time/; # Skip header
    next if /^-+\s+-+/;        # Skip separator line
    next if /^\s*$/;           # Skip empty

    # Parse 7z list output. 
    # Logic: Date(0) Time(1) Attr(2) Size(3) Compressed(4) Name(5)
    # Note: Directories in your snippet lack size/compressed columns.
    
    my $line = $_;
    my ($date, $time, $attr, $rest) = split(/\s+/, $line, 4);
    
    # Handle Directory (D....) which implies missing size columns
    if ($attr =~ /^D/) {
        # The rest of the line is just the name, but might have leading whitespace
        $rest =~ s/^\s+//;
        my $path = $rest;
        # 7z usually lists dirs without leading slash, we normalize
        $path = "$toplevel_dir/$path"; 
        $path =~ s|/$||; # Remove trailing slash
        $dirs{$path} = 1;
        next;
    }

    # Handle Files
    # We need to split $rest to get Size, Compressed, Name
    # $rest contains: "Size   Compressed  Name"
    my ($size, $compressed, $name) = split(/\s+/, $rest, 3);
    
    # Validation: ensure we have numbers where expected
    next unless defined $name;

    # Normalize path
    my $full_path = "$toplevel_dir/$name";
    my $dir       = dirname($full_path);
    my $filename  = basename($full_path);

    # Ensure parent dir exists in our map
    $dirs{$dir} = 1;

    # Store file entry: [Name, CompressedSize]
    # We substitute logical size with compressed size for the visualization
    push @{$files{$dir}}, [$filename, $compressed];
}

# Output the tree in QDirStat cache format
# Order: Directory entry, then its files.

foreach my $dir (sort keys %dirs) {
    # Encode spaces and special chars
    my $enc_dir = uri_escape($dir, "\x00-\x20%");
    
    # D <path> <size> <uid> <gid> <perm> <mtime>
    # Size 0 for dirs (qdirstat calculates it), fake uid/gid/mtime
    print "D $enc_dir\t0\t0\t0\t0755\t0\n";

    if (exists $files{$dir}) {
        foreach my $file_ref (@{$files{$dir}}) {
            my ($name, $size) = @$file_ref;
            my $enc_name = uri_escape($name, "\x00-\x20%");
            
            # F <name> <size> <uid> <gid> <perm> <mtime>
            # Use COMPRESSED size as the size value
            print "F $enc_name\t$size\t0\t0\t0644\t0\n";
        }
    }
}