[package]
name = "mapserver"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.16"
axum = "0.8"
rusqlite = "0.40.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.1", features = ["fs"] }
tower_governor = "0.8.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

[dev-dependencies]
tempfile = "3.27.0"
